r"""For specifying the output parameters for HRTEM simulations.

"""



#####################################
## Load libraries/packages/modules ##
#####################################

# For performing deep copies of objects.
import copy



# For validating and converting objects.
import czekitout.check
import czekitout.convert

# For defining classes that support enforced validation, updatability,
# pre-serialization, and de-serialization.
import fancytypes



# For validating instances of the class
# :class:`prismatique.hrtem.system.ModelParams`.
import prismatique.hrtem.system

# For validating instances of the classes
# :class:`prismatique.sample.ModelParams`, and
# :class:`prismatique.sample.PotentialSliceSubsetIDs`; and for calculating
# quantities related to the modelling of the sample.
import prismatique.sample

# For validating, pre-serializing, and de-pre-serializing instances of the class
# :class:`prismatique.hrtem.image.Params`.
import prismatique.hrtem.image

# For postprocessing HRTEM intensity images.
import prismatique._signal

# For generating tilts used in HRTEM simulations.
import prismatique.tilt



############################
## Authorship information ##
############################

__author__     = "Matthew Fitzpatrick"
__copyright__  = "Copyright 2023"
__credits__    = ["Matthew Fitzpatrick"]
__maintainer__ = "Matthew Fitzpatrick"
__email__      = "mrfitzpa@uvic.ca"
__status__     = "Development"



##################################
## Define classes and functions ##
##################################

# List of public objects in objects.
__all__ = ["Params",
           "data_size"]



def _check_and_convert_output_dirname(ctor_params):
    kwargs = {"obj": ctor_params["output_dirname"],
              "obj_name": "output_dirname"}
    output_dirname = czekitout.convert.to_str_from_path_like(**kwargs)
    
    return output_dirname



def _pre_serialize_output_dirname(output_dirname):
    serializable_rep = output_dirname

    return serializable_rep



def _de_pre_serialize_output_dirname(serializable_rep):
    output_dirname = serializable_rep

    return output_dirname



def _check_and_convert_max_data_size(ctor_params):
    kwargs = {"obj": ctor_params["max_data_size"],
              "obj_name": "max_data_size"}
    max_data_size = czekitout.convert.to_positive_int(**kwargs)
    
    return max_data_size



def _pre_serialize_max_data_size(max_data_size):
    serializable_rep = max_data_size

    return serializable_rep



def _de_pre_serialize_max_data_size(serializable_rep):
    max_data_size = serializable_rep

    return max_data_size



def _check_and_convert_image_params(ctor_params):
    check_and_convert_image_params = \
        prismatique.hrtem.image._check_and_convert_image_params
    image_params = \
        check_and_convert_image_params(ctor_params)
    
    return image_params



def _pre_serialize_image_params(image_params):
    pre_serialize_image_params = \
        prismatique.hrtem.image._pre_serialize_image_params
    serializable_rep = \
        pre_serialize_image_params(image_params)

    return serializable_rep



def _de_pre_serialize_image_params(serializable_rep):
    de_pre_serialize_image_params = \
        prismatique.hrtem.image._de_pre_serialize_image_params
    image_params = \
        de_pre_serialize_image_params(serializable_rep)

    return image_params



def _check_and_convert_save_potential_slices(ctor_params):
    kwargs = {"obj": ctor_params["save_potential_slices"],
              "obj_name": "save_potential_slices"}
    save_potential_slices = czekitout.convert.to_bool(**kwargs)
    
    return save_potential_slices



def _pre_serialize_save_potential_slices(save_potential_slices):
    serializable_rep = save_potential_slices

    return serializable_rep



def _de_pre_serialize_save_potential_slices(serializable_rep):
    save_potential_slices = serializable_rep

    return save_potential_slices



class Params(fancytypes.PreSerializableAndUpdatable):
    r"""The output parameters for HRTEM simulations.

    See the documentation for the class :class:`prismatique.hrtem.image.Params`
    for a discussion on HRTEM image wavefunctions and intensities that is
    relevant to the discussion on this page.  

    Upon the completion of a HRTEM simulation, ``prismatique`` can optionally
    save a variety of different HRTEM data to a set of HDF5 files based on the
    specifications of the user. This is done by taking the original output file
    generated by ``prismatic``, and then restructuring it into one or more
    output files. If the output parameters specify that intensity data be saved,
    then said data is extracted from the original ``prismatic`` output files,
    postprocessed, and written to a new file with basename
    ``"hrtem_sim_intensity_output.h5"`` in a more readable layout. This new
    output file has the following structure:

    - metadata: <HDF5 group>
    
      * r_x: <HDF5 1D dataset>
        
        + dim 1: "r_x idx"
        + units: "Å"

      * r_y: <HDF5 1D dataset>
        
        + dim 1: "r_y idx"
        + units: "Å"

    - data: <HDF5 group>

      * intensity_image: <HDF5 2D dataset>
        
        + dim 1: "r_y idx"
        + dim 2: "r_x idx"
        + units: "dimensionless"

    Note that the sub-bullet points listed immediately below a given HDF5
    dataset display the HDF5 attributes associated with said HDF5 dataset. Each
    HDF5 scalar and dataset has a ``"units"`` attribute which, as the name
    suggests, indicates the units in which said data [i.e. the scalar or
    dataset] is expressed. Each HDF5 dataset will also have a set of attributes
    with names of the form ``"dim {}".format(i)`` with ``i`` being an integer
    ranging from 1 to the rank of said HDF5 dataset. Attribute ``"dim
    {}".format(i)`` of a given HDF5 dataset labels the :math:`i^{\text{th}}`
    dimension of the underlying array of the dataset. Most of these dimension
    labels should be self-explanatory but for clarification: "idx" is short for
    "index"; "avg" is short for "average"; and "r_x" and "r_y" refer to the
    :math:`x`- and :math:`y`-coordinates in the discretized real-space.

    If the output parameters specify that complex-valued wavefunction data be
    saved, then said data is extracted from the original ``prismatic`` output
    files, and written to a new set of files: one file per frozen phonon/atomic
    configuration subset. Note that, unlike the intensity data, the
    complex-valued wavefunction data is not postprocessed. See the documentation
    for the class :class:`prismatique.thermal.Params` for a discussion on frozen
    phonon configurations and their grouping into subsets. For the ``i`` th
    frozen phonon configuration subset, the corresponding wavefunction data is
    saved to the file with basename
    ``"hrtem_sim_wavefunction_output_of_subset_"+str(i)+".h5"``. Each one of
    these new output files has the following structure:

    - metadata: <HDF5 group>
    
      * tilts: <HDF5 2D dataset>
        
        + dim 1: "tilt idx"
        + dim 2: "vector component idx [0->x, 1->y]"
        + units: "mrad"

      * defocii: <HDF5 1D dataset>
        
        + dim 1: "defocus idx"
        + units: "Å"

      * r_x: <HDF5 1D dataset>
        
        + dim 1: "r_x idx"
        + units: "Å"

      * r_y: <HDF5 1D dataset>
        
        + dim 1: "r_y idx"
        + units: "Å"

    - data: <HDF5 group>

      * image_wavefunctions: <HDF5 5D dataset>
        
        + dim 1: "atomic config idx"
        + dim 2: "defocus idx"
        + dim 3: "tilt idx"
        + dim 4: "r_y idx"
        + dim 5: "r_x idx"
        + units: "dimensionless"

    ``prismatique`` can also optionally save the "potential slice" [i.e.
    Eq. :eq:`coarse_grained_potential_1`] data for each subset of frozen phonon
    configurations into separate HDF5 output files by extracting said data from
    the original ``prismatic`` output files. See the documentation for the class
    :class:`prismatique.thermal.Params` for a discussion on frozen phonon
    configurations their grouping into subsets. For the ``i`` th subset, the
    corresponding potential slice data is saved to an HDF5 output file with
    basename ``"potential_slices_"+str(i)+".h5"``. Unlike the output data in the
    file ``"hrtem_simulation_output.h5"``, the layout of the potential slice
    data is kept the same as that found in the original file [i.e. the same HDF5
    paths are used].  The same layout needs to be used in order for
    ``prismatic`` to be able to successfully import/load pre-calculated
    potential slice data for a future simulation.

    It is beyond the scope of the documentation to describe the structure of the
    potential slice output files. Users can analyze the data in these output
    files with the help of the tools found in the module
    :mod:`prismatique.load`.

    The last file that is always generated after running a HRTEM simulation is a
    JSON file that contains, in a serialized format, the simulation parameters
    used. This file has the basename ``"hrtem_simulation_parameters.json"``.

    Parameters
    ----------
    output_dirname : `str`, optional
        The relative or absolute path to the directory in which all output files
        are to be saved. If the directory doesn't exist upon saving the output 
        files, it will be created if possible.
    max_data_size : `int`, optional
        The data size limit, in bytes, of the HRTEM simulation output to be
        generated. If the output to be generated would require a data size
        larger than the aforementioned limit, then an exception is raised and
        the HRTEM simulation is not performed. Note that data size due to HDF5
        file overhead and metadata are not taken into account.
    image_params : :class:`prismatique.hrtem.image.Params` | `None`, optional
        The simulation parameters related to image wavefunctions and
        intensities, which includes parameters specifying what kind of image
        output should be saved, if any at all. If ``image_params`` is set to
        `None` [i.e. the default value], then the aforementioned parameters are
        set to default values.
    save_potential_slices : `bool`, optional
        If ``save_potential_slices`` is set to ``True``, then for each frozen
        phonon configuration subset, the corresponding potential slice data is
        written to the file with the basename
        ``"potential_slices_of_subset_"+str(i)+".h5"``, with ``i`` being the 
        subset index. If ``save_potential_slices`` is set to ``False``, then no
        potential slice data is saved.

    Attributes
    ----------
    core_attrs : `dict`, read-only
        A `dict` representation of the core attributes: each `dict` key is a
        `str` representing the name of a core attribute, and the corresponding
        `dict` value is the object to which said core attribute is set. The core
        attributes are the same as the construction parameters, except that 
        their values might have been updated since construction.

    """
    _validation_and_conversion_funcs = \
        {"output_dirname": _check_and_convert_output_dirname,
         "max_data_size": _check_and_convert_max_data_size,
         "image_params": _check_and_convert_image_params,
         "save_potential_slices": _check_and_convert_save_potential_slices}

    _pre_serialization_funcs = \
        {"output_dirname": _pre_serialize_output_dirname,
         "max_data_size": _pre_serialize_max_data_size,
         "image_params": _pre_serialize_image_params,
         "save_potential_slices": _pre_serialize_save_potential_slices}

    _de_pre_serialization_funcs = \
        {"output_dirname": _de_pre_serialize_output_dirname,
         "max_data_size": _de_pre_serialize_max_data_size,
         "image_params": _de_pre_serialize_image_params,
         "save_potential_slices": _de_pre_serialize_save_potential_slices}
    
    def __init__(self,
                 output_dirname="sim_output_files",
                 max_data_size=2*10**9,
                 image_params=None,
                 save_potential_slices=False):
        ctor_params = {"output_dirname": output_dirname,
                       "max_data_size": max_data_size,
                       "image_params": image_params,
                       "save_potential_slices": save_potential_slices}
        fancytypes.PreSerializableAndUpdatable.__init__(self, ctor_params)

        return None



def _check_and_convert_output_params(ctor_params):
    output_params = copy.deepcopy(ctor_params["output_params"])
    if output_params is None:
        output_params = Params()

    kwargs = {"obj": output_params,
              "obj_name": "output_params",
              "accepted_types": (Params, type(None))}
    czekitout.check.if_instance_of_any_accepted_types(**kwargs)

    return output_params



def _pre_serialize_output_params(output_params):
    serializable_rep = output_params.pre_serialize()

    return serializable_rep



def _de_pre_serialize_output_params(serializable_rep):
    output_params = Params.de_pre_serialize(serializable_rep)

    return output_params



def data_size(hrtem_system_model_params, output_params=None):
    r"""Calculate the data size of the HRTEM simulation output that one could
    generate according to a given HRTEM system model, and output parameter set.

    Note that data size due to HDF5 file overhead and metadata are not taken
    into account.

    Parameters
    ----------
    hrtem_system_model_params : :class:`prismatique.hrtem.system.ModelParams`
        The simulation parameters related to the modelling of the HRTEM
        system. See the documentation for the class
        :class:`prismatique.hrtem.system.ModelParams` for a discussion on said
        parameters.
    output_params : :class:`prismatique.hrtem.output.Params` | `None`, optional
        The output parameters for the HRTEM simulation. See the documentation
        for the class :class:`prismatique.hrtem.output.Params` for a discussion
        on said parameters. If ``output_params`` is set to `None` [i.e. the
        default value], then the aforementioned simulation parameters are set to
        default values.

    Returns
    -------
    output_data_size : `int`
        The data size in units of bytes.

    """
    hrtem_syhrtem_model_params = \
        _check_hrtem_system_model_params(hrtem_system_model_params)
    temp_ctor_params = \
        {"output_params": output_params}
    output_params = \
        _check_and_convert_output_params(temp_ctor_params)
        
    output_data_size = _data_size(hrtem_system_model_params, output_params)
        
    return output_data_size



def _check_hrtem_system_model_params(hrtem_system_model_params):
    temp_ctor_params = \
        {"hrtem_system_model_params": hrtem_system_model_params}
    check_and_convert_hrtem_system_model_params = \
        prismatique.hrtem.system._check_and_convert_hrtem_system_model_params
    hrtem_system_model_params = \
        check_and_convert_hrtem_system_model_params(temp_ctor_params)

    sample_specification = \
        hrtem_system_model_params.core_attrs["sample_specification"]

    accepted_types = (prismatique.sample.ModelParams,
                      prismatique.sample.PotentialSliceSubsetIDs)
    prismatique.sample._check_sample_specification(sample_specification,
                                                   accepted_types)

    return hrtem_system_model_params



def _data_size(hrtem_system_model_params, output_params):    
    image_params = output_params.core_attrs["image_params"]

    output_data_size = 0

    kwargs = {"hrtem_system_model_params": hrtem_system_model_params,
              "output_params": output_params}
    if image_params.core_attrs["save_final_intensity"]:
        output_data_size += _data_size_of_intensity_output(**kwargs)
    if image_params.core_attrs["save_wavefunctions"]:
        output_data_size += _data_size_of_wavefunction_output(**kwargs)

    sample_specification = \
        hrtem_system_model_params.core_attrs["sample_specification"]    
    kwargs = \
        {"sample_specification": sample_specification}

    if output_params.core_attrs["save_potential_slices"]:
        output_data_size += \
            prismatique.sample._potential_slice_set_data_size(**kwargs)
            
    return output_data_size



def _data_size_of_intensity_output(hrtem_system_model_params, output_params):
    sample_specification = \
        hrtem_system_model_params.core_attrs["sample_specification"]
    image_params = \
        output_params.core_attrs["image_params"]
    postprocessing_seq = \
        image_params.core_attrs["postprocessing_seq"]
    num_pixels_in_postprocessed_2d_signal_space = \
        prismatique._signal._num_pixels_in_postprocessed_2d_signal_space

    kwargs = \
        {"sample_specification": sample_specification,
         "signal_is_cbed_pattern_set": False,
         "postprocessing_seq": postprocessing_seq}

    num_pixels_in_postprocessed_image = \
        num_pixels_in_postprocessed_2d_signal_space(**kwargs)

    size_of_single = 4  # In bytes.

    data_size_of_intensity_output = (size_of_single
                                     * num_pixels_in_postprocessed_image)

    return data_size_of_intensity_output



def _data_size_of_wavefunction_output(hrtem_system_model_params, output_params):
    sample_specification = \
        hrtem_system_model_params.core_attrs["sample_specification"]
    tilt_params = \
        hrtem_system_model_params.core_attrs["tilt_params"]
    gun_model_params = \
        hrtem_system_model_params.core_attrs["gun_model_params"]
    mean_beam_energy = \
        gun_model_params.core_attrs["mean_beam_energy"]
    defocal_offset_supersampling = \
        hrtem_system_model_params.core_attrs["defocal_offset_supersampling"]

    kwargs = \
        {"sample_specification": sample_specification}
    total_num_frozen_phonon_configs = \
        prismatique.sample._total_num_frozen_phonon_configs(**kwargs)

    tilt_series = prismatique.tilt._series(sample_specification,
                                           mean_beam_energy,
                                           tilt_params)

    kwargs["signal_is_cbed_pattern_set"] = \
        False
    num_pixels_in_unprocessed_image = \
        prismatique._signal._num_pixels_in_unprocessed_2d_signal_space(**kwargs)

    size_of_single = 4  # In bytes.
    size_of_complex_single = 2 * size_of_single  # In bytes.

    data_size_of_wavefunction_output = (total_num_frozen_phonon_configs
                                        * defocal_offset_supersampling
                                        * len(tilt_series)
                                        * num_pixels_in_unprocessed_image
                                        * size_of_complex_single)

    return data_size_of_wavefunction_output



###########################
## Define error messages ##
###########################
